import type { Equipment } from '../types'

export const EQUIPMENT_LIST: Equipment[] = [
  // ─── Standard Equipment (10 items) ─────────────────────────────────────────
  {
    id: 'dental-chair',
    name: '診療椅',
    nameEn: 'Dental Chair',
    price: 500,
    assetValue: 600,
    imagePlaceholder: 'src/assets/images/equipment/dental-chair.png',
    isPremium: false,
    description: '基礎診療必備，提升診所專業形象',
  },
  {
    id: 'bp-monitor',
    name: '自動血壓計',
    nameEn: 'Auto BP Monitor',
    price: 300,
    assetValue: 350,
    imagePlaceholder: 'src/assets/images/equipment/bp-monitor.png',
    isPremium: false,
    description: '快速量測，提升患者信任',
  },
  {
    id: 'candy-dispenser',
    name: '兒童糖果機',
    nameEn: 'Kids Candy Dispenser',
    price: 200,
    assetValue: 220,
    imagePlaceholder: 'src/assets/images/equipment/candy-dispenser.png',
    isPremium: false,
    description: '讓小病患不再懼怕回診',
  },
  {
    id: 'e-stethoscope',
    name: '電子聽診器',
    nameEn: 'Electronic Stethoscope',
    price: 800,
    assetValue: 950,
    imagePlaceholder: 'src/assets/images/equipment/e-stethoscope.png',
    isPremium: false,
    description: '精準聆聽，早期發現異常',
  },
  {
    id: 'diag-display',
    name: '診斷顯示器',
    nameEn: 'Diagnostic Display',
    price: 1200,
    assetValue: 1400,
    imagePlaceholder: 'src/assets/images/equipment/diag-display.png',
    isPremium: false,
    description: '高解析螢幕，影像判讀更精確',
  },
  {
    id: 'disinfect-robot',
    name: '消毒機器人',
    nameEn: 'Disinfection Robot',
    price: 2000,
    assetValue: 2400,
    imagePlaceholder: 'src/assets/images/equipment/disinfect-robot.png',
    isPremium: false,
    description: '自動消毒，降低感染風險',
  },
  {
    id: 'surgery-lamp',
    name: '手術燈',
    nameEn: 'Surgical Lamp',
    price: 1500,
    assetValue: 1800,
    imagePlaceholder: 'src/assets/images/equipment/surgery-lamp.png',
    isPremium: false,
    description: '無陰影照明，手術更安全',
  },
  {
    id: 'emr-tablet',
    name: '電子病歷平板',
    nameEn: 'EMR Tablet',
    price: 600,
    assetValue: 700,
    imagePlaceholder: 'src/assets/images/equipment/emr-tablet.png',
    isPremium: false,
    description: '無紙化病歷，效率倍增',
  },
  {
    id: 'ear-thermometer',
    name: '耳溫槍',
    nameEn: 'Ear Thermometer',
    price: 150,
    assetValue: 170,
    imagePlaceholder: 'src/assets/images/equipment/ear-thermometer.png',
    isPremium: false,
    description: '一秒測溫，快速分流',
  },
  {
    id: 'massage-chair',
    name: '按摩椅',
    nameEn: 'Massage Chair',
    price: 1000,
    assetValue: 1100,
    imagePlaceholder: 'src/assets/images/equipment/massage-chair.png',
    isPremium: false,
    description: '提升候診體驗，回客率暴升',
  },

  // ─── Premium Equipment (5 items — Flash Sale only) ──────────────────────────
  {
    id: 'ai-mri',
    name: 'AI MRI 掃描儀',
    nameEn: 'AI MRI Scanner',
    price: 6000,
    assetValue: 9000,
    imagePlaceholder: 'src/assets/images/equipment/ai-mri.png',
    isPremium: true,
    description: '人工智慧輔助診斷，準確率業界第一',
  },
  {
    id: 'da-vinci-arm',
    name: '達文西手術臂',
    nameEn: "Da Vinci Surgical Arm",
    price: 9000,
    assetValue: 14000,
    imagePlaceholder: 'src/assets/images/equipment/da-vinci-arm.png',
    isPremium: true,
    description: '精準微創，手術風險降至最低',
  },
  {
    id: 'biochem-analyzer',
    name: '全自動生化分析儀',
    nameEn: 'Auto Biochem Analyzer',
    price: 7500,
    assetValue: 11000,
    imagePlaceholder: 'src/assets/images/equipment/biochem-analyzer.png',
    isPremium: true,
    description: '血液快篩 10 項，10 分鐘出報告',
  },
  {
    id: 'laser-eye',
    name: '雷射眼科系統',
    nameEn: 'Laser Eye System',
    price: 8000,
    assetValue: 12000,
    imagePlaceholder: 'src/assets/images/equipment/laser-eye.png',
    isPremium: true,
    description: '近視雷射一站完成，排程月月滿',
  },
  {
    id: 'mobile-ct',
    name: '行動式 CT',
    nameEn: 'Mobile CT Scanner',
    price: 9000,
    assetValue: 14000,
    imagePlaceholder: 'src/assets/images/equipment/mobile-ct.png',
    isPremium: true,
    description: '帶到哪、掃到哪，全身透視無死角',
  },
]

export const STANDARD_EQUIPMENT = EQUIPMENT_LIST.filter((e) => !e.isPremium)
export const PREMIUM_EQUIPMENT = EQUIPMENT_LIST.filter((e) => e.isPremium)
export const equipmentById = Object.fromEntries(EQUIPMENT_LIST.map((e) => [e.id, e]))
